package me.pfzh.hibernatelite.query;

import me.pfzh.hibernatelite.exception.HibernateLiteException;

import java.beans.Introspector;
import java.lang.invoke.SerializedLambda;
import java.lang.reflect.Method;

/**
 * Resolves entity field names from getter-style method references.
 *
 * <p>Examples:</p>
 *
 * <pre>
 * User::getName   → "name"
 * User::getAge    → "age"
 * User::isActive  → "active"
 * User::getURL    → "URL"
 * </pre>
 *
 * <p>This class is used by the query DSL to convert a type-safe method
 * reference into the corresponding entity property name required by
 * the JPA Criteria API.</p>
 *
 * <p>For example:</p>
 *
 * <pre>
 * db.query(User.class)
 *     .eq(User::getName, "Tom");
 * </pre>
 *
 * <p>The lambda expression {@code User::getName} is resolved to the
 * property name {@code "name"} before the query is passed to the
 * Criteria API.</p>
 *
 * <p><b>How it works:</b></p>
 *
 * <ol>
 *     <li>The method reference is represented at runtime as a lambda
 *         object generated by the JVM.</li>
 *     <li>Because {@link SFunction} extends {@link java.io.Serializable},
 *         the generated lambda class provides a synthetic
 *         {@code writeReplace()} method.</li>
 *     <li>Invoking {@code writeReplace()} returns a
 *         {@link SerializedLambda} containing information about the
 *         original method reference.</li>
 *     <li>{@link SerializedLambda#getImplMethodName()} is used to obtain
 *         the implementation method name, such as {@code "getName"}.</li>
 *     <li>The {@code get} or {@code is} prefix is removed.</li>
 *     <li>{@link Introspector#decapitalize(String)} converts the remaining
 *         property name into JavaBeans property naming conventions.</li>
 * </ol>
 *
 * <p>The use of {@code Introspector.decapitalize()} is important for
 * names containing consecutive uppercase letters. For example:</p>
 *
 * <pre>
 * getName → name
 * getURL  → URL
 * </pre>
 *
 * <p>Using a simple {@code toLowerCase()} operation would incorrectly
 * convert {@code getURL} into {@code uRL}.</p>
 *
 * <p>This class is package-private and stateless.</p>
 *
 * @author Pengfei Zhang
 * @since 2026/9/19
 */
final class LambdaResolver {

    /**
     * Prevents instantiation.
     *
     * <p>All functionality in this class is provided through static
     * methods, so creating instances would have no meaning.</p>
     */
    private LambdaResolver() {}

    /**
     * Resolves a getter-style method reference into an entity property name.
     *
     * <p>Examples:</p>
     *
     * <pre>
     * User::getName  → "name"
     * User::getAge   → "age"
     * User::isActive → "active"
     * </pre>
     *
     * <p>The method is generic so that the compiler can infer the exact
     * {@link SFunction} type used by the caller.</p>
     *
     * @param fn getter-style method reference
     * @param <T> entity type
     * @param <R> property return type
     * @return entity property name
     * @throws IllegalArgumentException if {@code fn} is {@code null}
     * @throws HibernateLiteException if the lambda cannot be resolved
     *                                or is not getter-style
     */
    static <T, R> String resolve(SFunction<T, R> fn) {

        /*
         * A null method reference cannot be resolved.
         *
         * Fail immediately instead of allowing a NullPointerException
         * to occur later during reflection.
         */
        if (fn == null) {
            throw new IllegalArgumentException("Method reference cannot be null");
        }

        /*
         * Extract the JVM-level representation of the lambda.
         *
         * For:
         *
         *     User::getName
         *
         * this gives us a SerializedLambda object containing metadata
         * about the referenced method.
         */
        SerializedLambda lambda = extractLambda(fn);

        /*
         * Get the actual implementation method name from the
         * SerializedLambda.
         *
         * Examples:
         *
         *     User::getName  → "getName"
         *     User::getAge   → "getAge"
         *     User::isActive → "isActive"
         */
        String methodName = lambda.getImplMethodName();

        /*
         * Convert the getter method name into the entity property name.
         *
         * Example:
         *
         *     "getName"
         *          ↓
         *     remove "get"
         *          ↓
         *     "Name"
         *          ↓
         *     decapitalize
         *          ↓
         *     "name"
         */
        return stripPrefix(methodName, fn);
    }

    /**
     * Extracts the {@link SerializedLambda} representation from a
     * serializable lambda or method reference.
     *
     * <p>The JVM-generated lambda class normally contains a synthetic
     * {@code writeReplace()} method. Invoking this method returns the
     * {@link SerializedLambda} describing the original lambda.</p>
     *
     * @param fn serializable lambda or method reference
     * @param <T> entity type
     * @param <R> property return type
     * @return serialized representation of the lambda
     * @throws HibernateLiteException if the lambda cannot be inspected
     */
    private static <T, R> SerializedLambda extractLambda(SFunction<T, R> fn) {
        try {
            /*
             * Find the synthetic writeReplace() method generated for
             * the serializable lambda.
             *
             * The method is not declared in SFunction itself.
             * It is generated on the concrete lambda class created
             * by the JVM.
             */
            Method writeReplace = fn.getClass().getDeclaredMethod("writeReplace");

            /*
             * writeReplace() is normally not accessible directly.
             *
             * Make it accessible so that reflection can invoke it.
             */
            writeReplace.setAccessible(true);

            /*
             * Invoke writeReplace().
             *
             * The returned object should be a SerializedLambda.
             *
             * We pass no arguments because writeReplace() has no
             * parameters.
             */
            Object result = writeReplace.invoke(fn);

            /*
             * Verify that the JVM returned the representation we expect.
             *
             * Pattern matching for instanceof simultaneously checks
             * the type and creates the local variable "lambda".
             */
            if (!(result instanceof SerializedLambda lambda)) {
                throw new HibernateLiteException(
                        "Method reference is not a lambda expression");
            }

            return lambda;
        } catch (NoSuchMethodException e) {

            /*
             * The generated lambda class does not contain
             * writeReplace().
             *
             * This usually means that the object is not the kind of
             * serializable lambda/method reference we expect.
             */
            throw new HibernateLiteException(
                    "Method reference is not a lambda expression "
                            + "(possibly optimized by the compiler)", e);
        } catch (ReflectiveOperationException e) {

            /*
             * Covers reflection-related failures such as:
             *
             * - IllegalAccessException
             * - InvocationTargetException
             * - etc.
             *
             * Convert the low-level reflection exception into the
             * framework's own exception type.
             */
            throw new HibernateLiteException(
                    "Failed to resolve lambda expression", e);
        }
    }

    /**
     * Converts a getter method name into a Java entity property name.
     *
     * <p>Supported getter styles:</p>
     *
     * <pre>
     * getName()  → "name"
     * getAge()   → "age"
     * isActive() → "active"
     * </pre>
     *
     * <p>The method must follow the JavaBeans getter naming convention.
     * Arbitrary methods such as {@code calculateName()} are rejected.</p>
     *
     * @param methodName implementation method name extracted from
     *                   {@link SerializedLambda}
     * @param fn original method reference, used for diagnostic messages
     * @param <T> entity type
     * @param <R> property return type
     * @return corresponding entity property name
     * @throws HibernateLiteException if the method is not getter-style
     */
    private static <T, R> String stripPrefix(String methodName, SFunction<T, R> fn) {
        String prefix;

        /*
         * Check for a standard JavaBean getXxx() getter.
         *
         * length() > 3 ensures that "get" itself is not accepted
         * as a property getter.
         */
        if (methodName.startsWith("get") && methodName.length() > 3) {
            prefix = "get";

        /*
         * Check for a boolean-style isXxx() getter.
         *
         * length() > 2 ensures that "is" itself is not accepted.
         */
        } else if (methodName.startsWith("is") && methodName.length() > 2) {
            prefix = "is";
        } else {

        /*
         * The query DSL expects getter-style method references
         * because it needs to derive an entity property name.
         *
         * For example:
         *
         *     User::calculateAge
         *
         * cannot safely be interpreted as an entity field name.
         */
            throw new HibernateLiteException(
                    "Method reference must be getter-style (getXxx / isXxx): "
                            + fn.getClass().getName() + "#" + methodName);
        }

        /*
         * Remove the getter prefix.
         *
         * Examples:
         *
         *     getName  → "Name"
         *     getURL   → "URL"
         *     isActive → "Active"
         */
        String propertyName = methodName.substring(prefix.length());

        /*
         * Convert the remaining method name according to the
         * JavaBeans capitalization rules.
         *
         * Examples:
         *
         *     "Name" → "name"
         *     "URL"  → "URL"
         *
         * The second behavior is important because JavaBeans considers
         * an initial sequence of uppercase letters to be intentional.
         */
        return Introspector.decapitalize(propertyName);
    }

}